<NotepadPlus>
    <Session activeView="1">
        <mainView activeIndex="0">
            <File firstVisibleLine="0" xOffset="0" scrollWidth="350" startPos="248" endPos="248" selMode="0" offset="0" wrapCount="1" lang="Normal Text" encoding="-1" userReadOnly="no" filename="C:\Program Files\WoW\_retail_\Interface\AddOns\ConRO_Priest\ConRO_Priest.toc" backupFilePath="" originalFileLastModifTimestamp="-153166124" originalFileLastModifTimestampHigh="30855056" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="-884573418" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="75" scrollWidth="728" startPos="95" endPos="95" selMode="0" offset="0" wrapCount="1" lang="Normal Text" encoding="-1" userReadOnly="no" filename="C:\Program Files\WoW\_retail_\Interface\AddOns\ConRO_Priest\changes.txt" backupFilePath="" originalFileLastModifTimestamp="-154071955" originalFileLastModifTimestampHigh="30855057" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="0" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="294" startPos="16" endPos="16" selMode="0" offset="0" wrapCount="1" lang="Lua" encoding="-1" userReadOnly="no" filename="C:\Program Files\WoW\_retail_\Interface\AddOns\ConRO_Priest\priest_ids.lua" backupFilePath="" originalFileLastModifTimestamp="1000686327" originalFileLastModifTimestampHigh="30853623" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="0" mapWrapIndentMode="-1" mapIsWrap="no" />
        </mainView>
        <subView activeIndex="1">
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1785" startPos="670" endPos="670" selMode="0" offset="0" wrapCount="1" lang="Lua" encoding="-1" userReadOnly="no" filename="C:\Program Files\WoW\_retail_\Interface\AddOns\ConRO_Priest\priest.lua" backupFilePath="" originalFileLastModifTimestamp="-1287926334" originalFileLastModifTimestampHigh="30855057" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="11776" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="763" startPos="779" endPos="779" selMode="0" offset="0" wrapCount="1" lang="Lua" encoding="-1" userReadOnly="no" filename="C:\Program Files\WoW\_retail_\Interface\AddOns\ConRO_Priest\priest_helpers.lua" backupFilePath="" originalFileLastModifTimestamp="-1804041582" originalFileLastModifTimestampHigh="30855057" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="1138524160" mapWrapIndentMode="-1" mapIsWrap="no" />
        </subView>
    </Session>
</NotepadPlus>
